language: rust
sudo: enabled
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
    - cargo build --verbose
    - cargo test --test lib --no-fail-fast --features "json"
    - cargo test --locked  --no-fail-fast --lib
    - cargo test --examples
    - cargo test --example json_to_edn --features "json"
    # - cargo run --example async --features "async"
