[package]
name = "edn-rs"
version = "0.1.0"
authors = ["Julia Naomi <jnboeira@outlook.com>"]
description = "Crate to parse and emit EDN"
repository = "https://github.com/naomijub/edn-rs"
keywords = ["EDN"]
license = "GNU General Public License, Version 3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
