[package]
name = "edn-rs"
version = "0.4.0"
authors = ["Julia Naomi <jnboeira@outlook.com>"]
description = "Crate to parse and emit EDN"
repository = "https://github.com/naomijub/edn-rs"
keywords = ["EDN"]
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"