name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --locked  --no-fail-fast --lib
    - name: Run int tests
      run: cargo test --test lib --no-fail-fast --features "json"
    - name: Examples
      run: |
        cargo test --example json_to_edn --features "json"
        cargo test --examples
    - name: FMT
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
